apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../manifests/login-theme/base
  - ../../manifests/groups-and-membership/overlays/public
  - ../../manifests/sealed-secrets/base
  - ../../manifests/calert/base

