apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ../../manifests/login-theme/base
  - ../../manifests/groups-and-membership/overlays/public
  - ../../manifests/ntp-config/base
  - ../../manifests/sealed-secrets/base
  - ../../manifests/calert/base
  - ../../manifests/alertmanager/base
  - ../../manifests/argocd-helm/overlays/argocd-notifications
  - ../../manifests/cert-manager/operator/base

