apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ../../manifests/apps/login-theme/base
  - ../../manifests/apps/groups-and-membership/base
  - ../../manifests/cluster-config/ntp-config/base
  - ../../manifests/apps/sealed-secrets/base
  - ../../manifests/apps/cert-manager/base

