apiVersion: v1
kind: Secret
metadata:
  name: calert-secret
  namespace: calert
stringData:
  CALERT_PROVIDERS__SAFE_SPACE__ENDPOINT: "https://chat.googleapis.com/v1/spaces/AAAAOj2vre0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=y9aHlQ5EgEn0xwD4v_9P31PAnkjE20bv1cX4Q66Gv5A%3D"
type: Opaque