apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-hetzner
spec:
  project: default
  source:
    path: deploy/cert-manager-webhook-hetzner
    repoURL: https://github.com/vadimkim/cert-manager-webhook-hetzner
    targetRevision: master
    helm: 
      values: |
        certManager:
          namespace: openshift-cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager-webhook
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
