apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAOSOV/yxY/dRsJ/JD55YWgeXT1VIwx+UrIChizIWATGb+YtbTB/SUIG8m2zRtt8kB/elaaLBya2W90hQ8O8hdCpFHNWzsqR6kh/p3e5HXAVuPa1VbHbI47sHR5MgBYc3RKPAp1AltH5FBfBEx3XlnGd9Nm1rmgFmcMpzBfaSCRv/q57vme/5uBZ9PDrsSNZco4VBigey4Rl9lvOq0xZpP7XcOq7UnsoFD+pbyw+HCGhCFab2ko4M8/UkaaGTicG88uzeF6Kc5KPbwCvNPF41QbCnalFVCuv20UVZOBd3ySG6fGDech1tJT4qKarFKzCLUJxgOM768hGdr2ufEPUvfxLWHwlk2r0JE0jYkyiCDCmRjBFwrTTE/uuLSWm+/tXaSI90S4jVytWKoPt0rG6V6VBoTW4DptTzmCZEDM+QA00w6Xw7QxLKaPK4YBe9D4v70rwZbGibCj8GgSM4ABUAfJ7kkRaTWWrIyoo7kk74IbyGPbxvUWv7Ezj7QrbO9MxNXtFSxrgtrMoK47X56sLBXCGvSTsy3S9P2EwMMUW9i4ia3yQPyBm1pwJFGHxizzwlVtzY2tbObavnwNoInf1+IwYl/nXxuhfEPsS92WuesnjyAhWtX2hWA9YjyLpM0tAas0xxSg41kGIN1+j7qW5jFxX5hsTPrX0aoiKNcGpk1uhHWpcVXiWQxUMn3TH01mI3mxyBJGJi3x+JNi9/h6wPMYFLksSX/a3zFyxv9wWAKUXVzdDlp10K9sdS4RS1l+fWj+ltmA7nNPWArYnyZJbrxbwWt+urs5C7aDrhnjdM8mo5LXeeaDzZhAie0eABoPHqfXLD+SiYtMwG3duFHeiUNwzo/oFR9brG22bBhUlQo6R9W+iMo4rnKd81V3kBhX5jluPUw9suZmc+SUjdF3UR1wMtXvV2tkEpyGG6xd+xx0QRhtnEdBgHojU9HOJq6OKGac5hl0miPPj64yNozNBfAVVL3SCyCqpvS5Vo57dzPNynhwkdScqRl4q02gDPyTqp2XFfUSuNam0o39IJrkDPNkEPePrj2jWp61EuIPy9jPnNZpShq/ofyjnXT6ieEU1Z/DiHwI3csDu2YNxXh4quUpZKsGOGH5Ieb3VgkFGNg7ijz4ZwP+K3xZtHaXYl76HNGyx2d7b3YEGJ4BKp8HgrmenjUQ9FqEfkhU5l+zfpZBSoNwbAYF82i0Y5k9clnKl+HlaQ3BtvmOxWzkBARagnzEKL8rDpUIRIKNS1IArWqNT80oykWbHi9BVK1It7+iGgU1Y+rEbG64BvxU1PMG+TqKgt8W3Qp6cAlhxEv0hJgm3oghgTfVHm3pmHbIG7WmOBiaUBjPRtTQdhYw7jeAncOvma/g7AuxCJ+uSf3kgwC70QWBWFuvBMas1mKBdrWg+S3Jp/ZbUPYuES/SachbKJVQkPlxja/uqo19i8UJ6e8GTyVIKkXIv3phCPwE3JrHWQf/aTm86XN48eLXq6UZWyFB23F3FT/Gz3pJyZLwpG2eCNEVVje4QWroU2gUMBY/pLdqXoN5+2uMMdt3jjsDqO43tVd+LSNSCJnX3zxkmiCTM0BTbYi9Fv68sIRBXKFMfcGlITxQUvz2EszFJ7SCIkaotMbMqYxcAE1eb+8HCWbnhkCNnZ717w4CZWtWv+9tTlE1YJqXzv68fOPLcZ7qlG4G8YvjOKE9eD/b5phoo1Rql/TSHXw2NiEXxa+pi06EF4pIW4MizU8mrCjeqLQJdeNKrf6Yi020Q0Kua5zKJEjsRzkxLeuP6N7pKcnu6EXWacK6DlRy3O0tMTlBDVhc+2xRwOTD3HTcaCAA5qGB+HvtBK/R1WGpffFnsg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: alertmanager-main
      namespace: openshift-monitoring
    type: Opaque

