apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: "jonas@janz.digital"
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: jonas@janz.digital
            apiKeySecretRef:
              name: cloudflare-api-token
              key: api-token