- op: add
  path: /spec/source/helm
  value:
    values: |
      nameOverride: custom-argo
      redis:  
        securityContext:
          runAsUser: 1000760997
      openshift:
        enabled: true
      server:  
        route:
          enabled: true     
      
      
      
      
            