apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCBsQrztH2U8NgLQVdMdG8j/hV/Rl3vizzVQ/3/g/jdwLR84VEPct42m5hKIfsto2lHjOc76RpgN6njjOMEiaPTsS6q/mbiMsDzJileveZmAXjihIOh96GSxuN1yQ+OkdIDTGdQjXD/hhpAMeUsUt34U3S53NKy8WHfFCOr1ZqqPgtnVLcjOdcmfwY7pY0iuml98rhx3/drjK8pgn/MqNMFcU2m9CtSDq3T2VQMCBh95ZAKrUXa8dL7dMzS4JzwYySoGTZ2ZJn/vQ+eRJEtQnTSqa56v0ZV9c5FK7RJNIuU54aUj3H4eLunkFSlfmWwJsUScbjqVIbFhFrrVwRcjVy441gJQgVnY2hPefSzNCICEnEOddGF3T/rxPGouE/WyA9xYS14yrU4Vt1NAzwH9eWN0SLaZZdt4uRASszh3xI1A9EZnvyF5/fALtnSyjnFPVlHSbDO4bwWLUa6WnKZLv2cPYjMuHIS+2/xWOhhViH/Zo8eSySsQexnrDCCYWlN65RvjWCNL4DAza/q8Umk14dlArRwrt1LXqvUNE+eRpshk/gy30QiuMw/u+I264HHZA7kuriHSa4Eths7UmeFXfDqplh3V9FYwr0xTv6sbOyDme32luUd3iKqoa74p10V/RoskzTUF94rhsmyiAl9WKthlSbbPThNrx4LXC52IhGDHaZOSG8bdliZtQvoM0gjwgNU0t1ZSk/Q6UOiy8da/FC5z5t+ZwKD76Eb6q45F3xzf4Ec4kTJOwL3i3txJhARVBzsk6n3mlx+29vAoOGKEJgayFIqbdqBDn0t4UUIXb35Uzmv8MlkDtK9omkxIHmbFWGiyO7o5iW/hyHIDolktyrQLcHH85MkTmam4DqkTBFWQCtVZk7u1tAAtVSjgNbAYQjj2TPdMSqeKuaak07rjRPO6RrlnUKUoEhAy4JkUl0p2N6xRtnoz0Icf0M243AnZPkEBvNkEFUUYPqFtcOeZVLf+p9MSNzrH3uEhbsXHWp+DdtfuJAMh4f3GAQXfrjjzJFfJL8JxQ5M17CIgtI1Ve8Z9cNS6V3ObTQd9rx+Mrf06Z9INFN7jt+GC3aQNKvfCbKkJ5170jjUSHsydzOM3iBHojWxb5HaMwuI4fpdTBXzfJElmsVRWUEHI/bDm1Tat5mfX7e9/3DkxssKrAhAdVSUmAvC78gW0iF/7rGA54WiCeH2oOsmNShRNkFCSSFs+slf/8zrYdHahHGgenrBGdhkOYr3GYHrhWHG5oKOlluCjgyL3UDsNwwyczI4XsDAgCvYyYwpoRRyFVO5N2Bqi/zc/FR7i64XtUn2lcb2oc0pmIcrHrCip1L2GkxcuurDklVFCPJbh2Wb/O/3P0U2EhJwS4tDJ6hz+85oDzn/M1D/GvhXLPE4c63ybdrpXd4Gl9ufWC/TGJW6ORsZNEqKhE1IWWIr+MJZWebunLus07ISpN6pdTCMQHvJssjXzadsGdo6+8bIfoLSYiCtshFm/2CmhYUSWEMnzm4o427j9bRFEGn7s6W8W3r3NgZN9MZfwgUmxT8EO91nH7sCv8caHBLdBj7bmKH05Xjd++9as64dZL28MeFe98RZ8TFKSJ4BM6/3NTUREx27eoPWVxq5pR4tHEVke+OwXTfuPal0myRdvNvkNe7UEvKJnywLiGlAzxWEVqGpu9NHsMddfQwWDiWP5m/8vPd2tiNQL4rNEhbIzoLtCNTlh8S8/oTlh3xl9CcNrgjX4AYlrfAVPS7izOMFi4K1RnM1vdjuI8tXtodbZzK9mZZEKZFBMKZD8GspiGUaVhIOFZlVLUb9NBkNJJXDCDy4rHy2Ad38rEbTHCRGt8VhClsXMuv11Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: alertmanager-main
      namespace: openshift-monitoring
    type: Opaque

