apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cluster-config/alertmanager/base/
    repoURL: https://github.com/PixelJonas/ocp-gitops
    targetRevision: main
    
    
